services:
  kokoclone:
    build:
      context: ..
      dockerfile: docker/cpu/Dockerfile
    ports:
      - "8890:8880"
    environment:
      KOKOCLONE_ENABLE_WEBUI: "true"
      KOKOCLONE_TEMP_DIR: /tmp/kokoclone
      KOKOCLONE_MAX_CONCURRENT_JOBS: "1"
    volumes:
      - huggingface-cache:/root/.cache/huggingface
      - model-cache:/app/model
      - voice-cache:/app/voice

volumes:
  huggingface-cache:
  model-cache:
  voice-cache:
